"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2exe
"""
from setuptools import setup

# from setuptools import setup
# import py2exe
# APP = 'demo.py'
# DATA_FILES = []
# OPTIONS = {
#         # this forces the inclusion of ctypes.util, which is required to load 
#         # the opengl win32 backend. Neither py2exe nor cx_freeze seem to
#         # be able to autodiscover this, which leads to application that 
#         # crash without printing an error
#         'packages': ['ctypes'],  
#         'includes': [],
#         'excludes':  ["PyQt6"],
#         'dist_dir': "dist"
#         }
    


# setup(
#     windows=['demo.py'],
#     data_files=DATA_FILES,
#     options={'py2exe': OPTIONS},
#     setup_requires=['py2exe'],
#         entry_points={
#         'console_scripts': [
#             'demo=demo:main',
#         ]
#       }
# )


# pyinstaller
setup(
    name="demo",
    version="1.1.0",
    description="Neurondemo",
    long_description_content_type="text/markdown",
    url="",
    author="pbm/lc",
    author_email="pmanis@med.unc.edu",
    license="MIT",
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 3",
    ],
    packages=["demo"],
    include_package_data=True,
    install_requires=[
        "pyqt6", "pyqtgraph", "numpy", "scipy",
    ],
    entry_points={"console_scripts": ["demo=demo.__main__:main"]},
)
